In [1]:
import numpy as np

l1=[1,2,3,4,5,6,7]

n1=np.array(l1)



In [2]:
n1


array([1, 2, 3, 4, 5, 6, 7])

In [3]:
l2=[1,2,3,4,5]
l3=[6,7,8,9,6]

n2=np.array([[l2],[l3]])

In [4]:
n2

array([[[1, 2, 3, 4, 5]],

       [[6, 7, 8, 9, 6]]])

In [8]:
n3 = np.zeros((2,3))
n3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
n4 = np.full((2,2),10)
n4

array([[10, 10],
       [10, 10]])

In [14]:
n5 = np.arange(10,20,2)
n5

array([10, 12, 14, 16, 18])

In [13]:
n1.shape

(7,)

In [17]:
n6=np.random.randint(100,200,10)
n6

array([106, 161, 135, 145, 101, 145, 151, 122, 113, 186])

In [23]:
l2=[1,2,3,4,5]
l3=[6,7,8,9,6]
l4=[9,8,7,6,5]

n2=np.array([[l2],[l3],[l4]])
n2

array([[[1, 2, 3, 4, 5]],

       [[6, 7, 8, 9, 6]],

       [[9, 8, 7, 6, 5]]])

In [26]:
l1=[1,2,3,4,5]
l2=[1,2,3,4,5]

n1=np.array(l1)
n2=np.array(l2)

In [28]:
np.vstack((n1,n2))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [29]:
np.hstack((n1,n2))


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [30]:
np.column_stack((n1,n2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [41]:

l1=[1,2,3,4,5]
l2=[5,6,7,8,3]

n1=np.array(l1)
n2=np.array(l2)
n1=n1+5
n1


array([ 6,  7,  8,  9, 10])

In [37]:
s1=np.sum((n1,n2),axis=1)
s1

array([15, 29])

In [34]:
a2 =np.setdiff1d(n1,n2)
a2

array([1, 2, 4])

In [42]:
a1=np.intersect1d(n1,n2)

a1

array([6, 7, 8])